/*
 * NCI EVS Rest API
 * Endpoints to support searching, metadata, and content retrieval for EVS terminologies. To learn more about how to interact with this api, see the <a href=\"https://github.com/NCIEVS/evsrestapi-client-SDK\">Github evsrestapi-client-SDK project.</a>
 *
 * The version of the OpenAPI document: 1.7.2.RELEASE
 * Contact: NCIAppSupport@nih.gov
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gov.nih.nci.evs.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConceptMap
 */
@Disabled
public class ConceptMapTest {
    private final ConceptMap model = new ConceptMap();

    /**
     * Model tests for ConceptMap
     */
    @Test
    public void testConceptMap() {
        // TODO: test ConceptMap
    }

    /**
     * Test the property 'uri'
     */
    @Test
    public void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'ct'
     */
    @Test
    public void ctTest() {
        // TODO: test ct
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'sourceName'
     */
    @Test
    public void sourceNameTest() {
        // TODO: test sourceName
    }

    /**
     * Test the property 'sourceTermType'
     */
    @Test
    public void sourceTermTypeTest() {
        // TODO: test sourceTermType
    }

    /**
     * Test the property 'sourceCode'
     */
    @Test
    public void sourceCodeTest() {
        // TODO: test sourceCode
    }

    /**
     * Test the property 'sourceTerminology'
     */
    @Test
    public void sourceTerminologyTest() {
        // TODO: test sourceTerminology
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'rank'
     */
    @Test
    public void rankTest() {
        // TODO: test rank
    }

    /**
     * Test the property 'group'
     */
    @Test
    public void groupTest() {
        // TODO: test group
    }

    /**
     * Test the property 'rule'
     */
    @Test
    public void ruleTest() {
        // TODO: test rule
    }

    /**
     * Test the property 'targetName'
     */
    @Test
    public void targetNameTest() {
        // TODO: test targetName
    }

    /**
     * Test the property 'targetTermType'
     */
    @Test
    public void targetTermTypeTest() {
        // TODO: test targetTermType
    }

    /**
     * Test the property 'targetCode'
     */
    @Test
    public void targetCodeTest() {
        // TODO: test targetCode
    }

    /**
     * Test the property 'targetTerminology'
     */
    @Test
    public void targetTerminologyTest() {
        // TODO: test targetTerminology
    }

    /**
     * Test the property 'targetTerminologyVersion'
     */
    @Test
    public void targetTerminologyVersionTest() {
        // TODO: test targetTerminologyVersion
    }

    /**
     * Test the property 'targetTermGroup'
     */
    @Test
    public void targetTermGroupTest() {
        // TODO: test targetTermGroup
    }

}
