/*
NCI EVS Rest API

Testing HistoryEndpointsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package evs

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_evs_HistoryEndpointsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HistoryEndpointsAPIService GetReplacements", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var terminology string
		var code string

		resp, httpRes, err := apiClient.HistoryEndpointsAPI.GetReplacements(context.Background(), terminology, code).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HistoryEndpointsAPIService GetReplacementsFromList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var terminology string

		resp, httpRes, err := apiClient.HistoryEndpointsAPI.GetReplacementsFromList(context.Background(), terminology).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
