/**
 * NCI EVS Rest API
 * Endpoints to support searching, metadata, and content retrieval for EVS terminologies. To learn more about how to interact with this api, see the <a href=\"https://github.com/NCIEVS/evsrestapi-client-SDK\">Github evsrestapi-client-SDK project.</a>
 *
 * OpenAPI spec version: 2.4.0.RELEASE
 * Contact: NCIAppSupport@nih.gov
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Paths } from '../models/Paths';
import { HttpFile } from '../http/http';

/**
* Generally unset, this is used for certain special cases
*/
export class Extensions {
    /**
    * URI for this element in an rdf-based source file
    */
    'uri'?: string;
    /**
    * Used to indicate the total amount of data in cases where a limit is being applied
    */
    'ct'?: number;
    'isDisease'?: boolean;
    'isDiseaseGrade'?: boolean;
    'isDiseaseStage'?: boolean;
    'isMainType'?: boolean;
    'isSubtype'?: boolean;
    'isBiomarker'?: boolean;
    'isReferenceGene'?: boolean;
    'mainMenuAncestors'?: Array<Paths>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string",
            "format": ""
        },
        {
            "name": "ct",
            "baseName": "ct",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "isDisease",
            "baseName": "isDisease",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isDiseaseGrade",
            "baseName": "isDiseaseGrade",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isDiseaseStage",
            "baseName": "isDiseaseStage",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isMainType",
            "baseName": "isMainType",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isSubtype",
            "baseName": "isSubtype",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isBiomarker",
            "baseName": "isBiomarker",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isReferenceGene",
            "baseName": "isReferenceGene",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "mainMenuAncestors",
            "baseName": "mainMenuAncestors",
            "type": "Array<Paths>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Extensions.attributeTypeMap;
    }

    public constructor() {
    }
}

