/*
NCI EVS Rest API

Endpoints to support searching, metadata, and content retrieval for EVS terminologies. To learn more about how to interact with this api, see the <a href=\"https://github.com/NCIEVS/evsrestapi-client-SDK\">Github evsrestapi-client-SDK project.</a>

API version: 1.7.2.RELEASE
Contact: NCIAppSupport@nih.gov
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package evs

import (
	"encoding/json"
)

// checks if the StatisticsEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatisticsEntry{}

// StatisticsEntry Represents an entry in a statistics table
type StatisticsEntry struct {
	// Code for what this statistic is measuring
	Code *string `json:"code,omitempty"`
	// Key defining an additional element to the statistic
	Key *string `json:"key,omitempty"`
	// Value of the statistic
	Value *string `json:"value,omitempty"`
}

// NewStatisticsEntry instantiates a new StatisticsEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatisticsEntry() *StatisticsEntry {
	this := StatisticsEntry{}
	return &this
}

// NewStatisticsEntryWithDefaults instantiates a new StatisticsEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatisticsEntryWithDefaults() *StatisticsEntry {
	this := StatisticsEntry{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *StatisticsEntry) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsEntry) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *StatisticsEntry) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *StatisticsEntry) SetCode(v string) {
	o.Code = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *StatisticsEntry) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsEntry) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *StatisticsEntry) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *StatisticsEntry) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *StatisticsEntry) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsEntry) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *StatisticsEntry) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *StatisticsEntry) SetValue(v string) {
	o.Value = &v
}

func (o StatisticsEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatisticsEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableStatisticsEntry struct {
	value *StatisticsEntry
	isSet bool
}

func (v NullableStatisticsEntry) Get() *StatisticsEntry {
	return v.value
}

func (v *NullableStatisticsEntry) Set(val *StatisticsEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableStatisticsEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableStatisticsEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatisticsEntry(val *StatisticsEntry) *NullableStatisticsEntry {
	return &NullableStatisticsEntry{value: val, isSet: true}
}

func (v NullableStatisticsEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatisticsEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


