/*
 * NCI EVS Rest API
 * Endpoints to support searching, metadata, and content retrieval for EVS terminologies. To learn more about how to interact with this api, see the <a href=\"https://github.com/NCIEVS/evsrestapi-client-SDK\">Github evsrestapi-client-SDK project.</a>
 *
 * The version of the OpenAPI document: 2.3.0.RELEASE
 * Contact: NCIAppSupport@nih.gov
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gov.nih.nci.evs.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import gov.nih.nci.evs.api.model.Qualifier;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Represents an entry in a table of associations between two concepts
 */
@JsonPropertyOrder({
  AssociationEntry.JSON_PROPERTY_URI,
  AssociationEntry.JSON_PROPERTY_CT,
  AssociationEntry.JSON_PROPERTY_CODE,
  AssociationEntry.JSON_PROPERTY_TYPE,
  AssociationEntry.JSON_PROPERTY_RELATED_CODE,
  AssociationEntry.JSON_PROPERTY_RELATED_NAME,
  AssociationEntry.JSON_PROPERTY_SOURCE,
  AssociationEntry.JSON_PROPERTY_HIGHLIGHT,
  AssociationEntry.JSON_PROPERTY_QUALIFIERS,
  AssociationEntry.JSON_PROPERTY_TERMINOLOGY,
  AssociationEntry.JSON_PROPERTY_VERSION,
  AssociationEntry.JSON_PROPERTY_ASSOCIATION,
  AssociationEntry.JSON_PROPERTY_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-09T19:13:16.571423-07:00[America/Los_Angeles]", comments = "Generator version: 7.5.0")
public class AssociationEntry {
  public static final String JSON_PROPERTY_URI = "uri";
  private String uri;

  public static final String JSON_PROPERTY_CT = "ct";
  private Integer ct;

  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_RELATED_CODE = "relatedCode";
  private String relatedCode;

  public static final String JSON_PROPERTY_RELATED_NAME = "relatedName";
  private String relatedName;

  public static final String JSON_PROPERTY_SOURCE = "source";
  private String source;

  public static final String JSON_PROPERTY_HIGHLIGHT = "highlight";
  private String highlight;

  public static final String JSON_PROPERTY_QUALIFIERS = "qualifiers";
  private List<Qualifier> qualifiers = new ArrayList<>();

  public static final String JSON_PROPERTY_TERMINOLOGY = "terminology";
  private String terminology;

  public static final String JSON_PROPERTY_VERSION = "version";
  private String version;

  public static final String JSON_PROPERTY_ASSOCIATION = "association";
  private String association;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public AssociationEntry() { 
  }

  public AssociationEntry uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * URI for this element in an rdf-based source file
   * @return uri
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUri() {
    return uri;
  }


  @JsonProperty(JSON_PROPERTY_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUri(String uri) {
    this.uri = uri;
  }


  public AssociationEntry ct(Integer ct) {
    this.ct = ct;
    return this;
  }

   /**
   * Used to indicate the total amount of data in cases where a limit is being applied
   * @return ct
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCt() {
    return ct;
  }


  @JsonProperty(JSON_PROPERTY_CT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCt(Integer ct) {
    this.ct = ct;
  }


  public AssociationEntry code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Code on the &#39;from&#39; side of the association
   * @return code
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }


  public AssociationEntry type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Relationship type
   * @return type
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public AssociationEntry relatedCode(String relatedCode) {
    this.relatedCode = relatedCode;
    return this;
  }

   /**
   * Code on the &#39;to&#39; side of the association
   * @return relatedCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelatedCode() {
    return relatedCode;
  }


  @JsonProperty(JSON_PROPERTY_RELATED_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelatedCode(String relatedCode) {
    this.relatedCode = relatedCode;
  }


  public AssociationEntry relatedName(String relatedName) {
    this.relatedName = relatedName;
    return this;
  }

   /**
   * Preferred name of the related code
   * @return relatedName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelatedName() {
    return relatedName;
  }


  @JsonProperty(JSON_PROPERTY_RELATED_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelatedName(String relatedName) {
    this.relatedName = relatedName;
  }


  public AssociationEntry source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Relationship source
   * @return source
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSource() {
    return source;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(String source) {
    this.source = source;
  }


  public AssociationEntry highlight(String highlight) {
    this.highlight = highlight;
    return this;
  }

   /**
   * Used by search calls to provide information for highlighting a view of results
   * @return highlight
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HIGHLIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHighlight() {
    return highlight;
  }


  @JsonProperty(JSON_PROPERTY_HIGHLIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHighlight(String highlight) {
    this.highlight = highlight;
  }


  public AssociationEntry qualifiers(List<Qualifier> qualifiers) {
    this.qualifiers = qualifiers;
    return this;
  }

  public AssociationEntry addQualifiersItem(Qualifier qualifiersItem) {
    if (this.qualifiers == null) {
      this.qualifiers = new ArrayList<>();
    }
    this.qualifiers.add(qualifiersItem);
    return this;
  }

   /**
   * Type/value qualifiers on the relationship
   * @return qualifiers
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUALIFIERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Qualifier> getQualifiers() {
    return qualifiers;
  }


  @JsonProperty(JSON_PROPERTY_QUALIFIERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQualifiers(List<Qualifier> qualifiers) {
    this.qualifiers = qualifiers;
  }


  public AssociationEntry terminology(String terminology) {
    this.terminology = terminology;
    return this;
  }

   /**
   * Terminology abbreviation, e.g. &#39;nci&#39;
   * @return terminology
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TERMINOLOGY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTerminology() {
    return terminology;
  }


  @JsonProperty(JSON_PROPERTY_TERMINOLOGY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTerminology(String terminology) {
    this.terminology = terminology;
  }


  public AssociationEntry version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Terminology version, e.g. &#39;23.11d&#39;
   * @return version
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(String version) {
    this.version = version;
  }


  public AssociationEntry association(String association) {
    this.association = association;
    return this;
  }

   /**
   * Type of relationship between code and related code
   * @return association
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASSOCIATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAssociation() {
    return association;
  }


  @JsonProperty(JSON_PROPERTY_ASSOCIATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssociation(String association) {
    this.association = association;
  }


  public AssociationEntry name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Preferred name of the code
   * @return name
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  /**
   * Return true if this AssociationEntry object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssociationEntry associationEntry = (AssociationEntry) o;
    return Objects.equals(this.uri, associationEntry.uri) &&
        Objects.equals(this.ct, associationEntry.ct) &&
        Objects.equals(this.code, associationEntry.code) &&
        Objects.equals(this.type, associationEntry.type) &&
        Objects.equals(this.relatedCode, associationEntry.relatedCode) &&
        Objects.equals(this.relatedName, associationEntry.relatedName) &&
        Objects.equals(this.source, associationEntry.source) &&
        Objects.equals(this.highlight, associationEntry.highlight) &&
        Objects.equals(this.qualifiers, associationEntry.qualifiers) &&
        Objects.equals(this.terminology, associationEntry.terminology) &&
        Objects.equals(this.version, associationEntry.version) &&
        Objects.equals(this.association, associationEntry.association) &&
        Objects.equals(this.name, associationEntry.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, ct, code, type, relatedCode, relatedName, source, highlight, qualifiers, terminology, version, association, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssociationEntry {\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    ct: ").append(toIndentedString(ct)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    relatedCode: ").append(toIndentedString(relatedCode)).append("\n");
    sb.append("    relatedName: ").append(toIndentedString(relatedName)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    highlight: ").append(toIndentedString(highlight)).append("\n");
    sb.append("    qualifiers: ").append(toIndentedString(qualifiers)).append("\n");
    sb.append("    terminology: ").append(toIndentedString(terminology)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    association: ").append(toIndentedString(association)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `uri` to the URL query string
    if (getUri() != null) {
      joiner.add(String.format("%suri%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUri()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `ct` to the URL query string
    if (getCt() != null) {
      joiner.add(String.format("%sct%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format("%scode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `relatedCode` to the URL query string
    if (getRelatedCode() != null) {
      joiner.add(String.format("%srelatedCode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRelatedCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `relatedName` to the URL query string
    if (getRelatedName() != null) {
      joiner.add(String.format("%srelatedName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRelatedName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `source` to the URL query string
    if (getSource() != null) {
      joiner.add(String.format("%ssource%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSource()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `highlight` to the URL query string
    if (getHighlight() != null) {
      joiner.add(String.format("%shighlight%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getHighlight()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `qualifiers` to the URL query string
    if (getQualifiers() != null) {
      for (int i = 0; i < getQualifiers().size(); i++) {
        if (getQualifiers().get(i) != null) {
          joiner.add(getQualifiers().get(i).toUrlQueryString(String.format("%squalifiers%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `terminology` to the URL query string
    if (getTerminology() != null) {
      joiner.add(String.format("%sterminology%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTerminology()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `version` to the URL query string
    if (getVersion() != null) {
      joiner.add(String.format("%sversion%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getVersion()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `association` to the URL query string
    if (getAssociation() != null) {
      joiner.add(String.format("%sassociation%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAssociation()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

