/*
 * NCI EVS Rest API
 * Endpoints to support searching, metadata, and content retrieval for EVS terminologies. To learn more about how to interact with this api, see the <a href=\"https://github.com/NCIEVS/evsrestapi-client-SDK\">Github evsrestapi-client-SDK project.</a>
 *
 * The version of the OpenAPI document: 2.3.0.RELEASE
 * Contact: NCIAppSupport@nih.gov
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gov.nih.nci.evs.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import gov.nih.nci.evs.api.model.ConceptMinimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Represents a path (or partial path) in a hierarchy
 */
@JsonPropertyOrder({
  Path.JSON_PROPERTY_URI,
  Path.JSON_PROPERTY_CT,
  Path.JSON_PROPERTY_DIRECTION,
  Path.JSON_PROPERTY_CONCEPTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-09T19:13:16.571423-07:00[America/Los_Angeles]", comments = "Generator version: 7.5.0")
public class Path {
  public static final String JSON_PROPERTY_URI = "uri";
  private String uri;

  public static final String JSON_PROPERTY_CT = "ct";
  private Integer ct;

  public static final String JSON_PROPERTY_DIRECTION = "direction";
  private Integer direction;

  public static final String JSON_PROPERTY_CONCEPTS = "concepts";
  private List<ConceptMinimal> concepts = new ArrayList<>();

  public Path() { 
  }

  public Path uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * URI for this element in an rdf-based source file
   * @return uri
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUri() {
    return uri;
  }


  @JsonProperty(JSON_PROPERTY_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUri(String uri) {
    this.uri = uri;
  }


  public Path ct(Integer ct) {
    this.ct = ct;
    return this;
  }

   /**
   * Used to indicate the total amount of data in cases where a limit is being applied
   * @return ct
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCt() {
    return ct;
  }


  @JsonProperty(JSON_PROPERTY_CT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCt(Integer ct) {
    this.ct = ct;
  }


  public Path direction(Integer direction) {
    this.direction = direction;
    return this;
  }

   /**
   * Direction of the map (1 means node-to-root, -1 means root-to-node)
   * @return direction
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIRECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDirection() {
    return direction;
  }


  @JsonProperty(JSON_PROPERTY_DIRECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDirection(Integer direction) {
    this.direction = direction;
  }


  public Path concepts(List<ConceptMinimal> concepts) {
    this.concepts = concepts;
    return this;
  }

  public Path addConceptsItem(ConceptMinimal conceptsItem) {
    if (this.concepts == null) {
      this.concepts = new ArrayList<>();
    }
    this.concepts.add(conceptsItem);
    return this;
  }

   /**
   * Concepts on the path
   * @return concepts
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONCEPTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ConceptMinimal> getConcepts() {
    return concepts;
  }


  @JsonProperty(JSON_PROPERTY_CONCEPTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConcepts(List<ConceptMinimal> concepts) {
    this.concepts = concepts;
  }


  /**
   * Return true if this Path object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Path path = (Path) o;
    return Objects.equals(this.uri, path.uri) &&
        Objects.equals(this.ct, path.ct) &&
        Objects.equals(this.direction, path.direction) &&
        Objects.equals(this.concepts, path.concepts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, ct, direction, concepts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Path {\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    ct: ").append(toIndentedString(ct)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    concepts: ").append(toIndentedString(concepts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `uri` to the URL query string
    if (getUri() != null) {
      joiner.add(String.format("%suri%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUri()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `ct` to the URL query string
    if (getCt() != null) {
      joiner.add(String.format("%sct%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `direction` to the URL query string
    if (getDirection() != null) {
      joiner.add(String.format("%sdirection%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDirection()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `concepts` to the URL query string
    if (getConcepts() != null) {
      for (int i = 0; i < getConcepts().size(); i++) {
        if (getConcepts().get(i) != null) {
          joiner.add(getConcepts().get(i).toUrlQueryString(String.format("%sconcepts%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

